name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v4
      with:
        name: p2psync
        path: target/p2psync
    # - name: Run tests
    #   run: cargo test --verbose
